# OrganizationAliases.py
# Try to solve the herculean task of people misspelling their company

AliasDict = { "360 Medlink" : "360Medlink",
              "ADNSolution" : "ADN Solution",
              "-" : None,
              "." : None,
              ":-}" : None,
              "None" : None,
              "none" : None,
              "self" : None,
              "freelance" : None,
              "Freelance" : None,
              "Freelancer" : None,
              "free lance" : None,
              "n/a" : None,
              "NA" : None,
              "N/A" : None,
<<<<<<< HEAD
              "na" : None,
              "rien" : None,
              "Independent" : None,
              "Independent Contractor" : None,
              "Self-employed" : None,
              "student" : None,
              "self empo." : None,
              "Private" : None,
              "Private Practice" : None,
              "Self" : None,
              "Self employed" : None,
              "Self-Employed" : None,
              "Startup" : None,
              "Travailleuse autonome" : None,
              "self empo" : None,
              "Health Professional" : None,
              "Agence de la sante publique du Canada" : u"Agence de la sant\u00e9 publique du Canada",
              "Anges Quebec" : "Anges Qu\u00e9bec",
              "Membre, Anges Qu\u00e9bec" : "Anges Qu\u00e9bec",
=======
              "Independent" : None,
              "Independent Contractor" : None,
              "Self-employed" : None,
              "Agence de la sante publique du Canada" : u"Agence de la sant\u00e9 publique du Canada",
              "Anges Quebec" : u"Anges Qu\u00e9bec",
>>>>>>> 194a3912654ce34ffd033e787aa232046b56a814
              "Association I.R.I.S. (Centre de crise)" : "Association IRIS",
              "BDC Healthcare Fund" : "BDC Venture Healthcare Fund",
              "BDC Venture Capital" : "BDC Venture Healthcare Fund",
              "BDC, Healthcare Fund" : "BDC Venture Healthcare Fund",
              "BDC Capital" : "BDC Venture Healthcare Fund",
              "CHU Sainte" : "CHU Sainte-Justine",
              "CHU Sainte Justine" : "CHU Sainte-Justine",
              "CHU Sainte-Justine Foundation" :"CHU Sainte-Justine",
              "CHU Ste Justine" : "CHU Sainte-Justine",
              "CHU ste Justine" : "CHU Sainte-Justine",
              "CHU Ste-Justine" : "CHU Sainte-Justine",
              "CHU-Ste-Justine" : "CHU Sainte-Justine",
              "Ste-Justine" : "CHU Sainte-Justine",
              "Ste-Justine MUCH" : "CHU Sainte-Justine",
              "chusjustine" : "CHU Sainte-Justine",
              "ste-justine hospital" : "CHU Sainte-Justine",
<<<<<<< HEAD
              "Sainte Justine Hospital" : "CHU Sainte-Justine",
=======
>>>>>>> 194a3912654ce34ffd033e787aa232046b56a814
              "centre de r\u00e9adaptation marie enfant" : "CHU Sainte-Justine",
              "Chu St-Justine" : "CHU Sainte-Justine",
              "COMITE DE USAGERS CHUM ST JUSTINE" : "CHU Sainte-Justine",
              "CHUSJ" : "CHU Sainte-Justine",
              "CCHU Sainte-Justine" : "CHU Sainte-Justine",
<<<<<<< HEAD
              "CHU Ste-Justine-Centre de r\u00e9adaptation Marie-Enfant"      : "CHU Sainte-Justine",
              "CHU Ste-Justine-Centre de r\u00e9adaptation Marie-Enfant" : "CHU Sainte-Justine",
              "Centre d ePromotion de la Sant\u00e9 - CHU Sainte-Justine" : "CHU Sainte-Justine",
              "Centre de promotion de la sant\u00e9 CHU Sainte-Justine" : "CHU Sainte-Justine",
=======
              "CHU Ste-Justine-Centre de réadaptation Marie-Enfant"      : "CHU Sainte-Justine",
              "CHU Ste-Justine-Centre de réadaptation Marie-Enfant" : "CHU Sainte-Justine",
              "Centre d ePromotion de la Sant\u00e9 - CHU Sainte-Justine" : "CHU Sainte-Justine",
              "Centre de promotion de la santé CHU Sainte-Justine" : "CHU Sainte-Justine",
>>>>>>> 194a3912654ce34ffd033e787aa232046b56a814
              "Centre de promotion de la sant\u00e9. CHU Sainte-Justine" : "CHU Sainte-Justine",
              "Centre hospitalier Universitaire Sainte Justine" : "CHU Sainte-Justine",
              "H\u00f4pital Ste-Justine" : "CHU Sainte-Justine",
              "Hopital Sainte Justine" : "CHU Sainte-Justine",
              "Hopital Ste-Justine" : "CHU Sainte-Justine",
<<<<<<< HEAD
              "Hopital Ste-Justine, Centre de r\u00e9adaptation Marie Enfant" : "CHU Sainte-Justine",
              "Ste-justine hospital" : "CHU Sainte-Justine",
              "Centre hospitalier universitaire de Montr\u00e9al" : "CHUM",
              "CHUM - H^tel-Dieu Hospital" : "CHUM",
              "CHUM - H\u00f4tel-Dieu Hospital" : "CHUM",
=======
              "Hopital Ste-Justine, Centre de réadaptation Marie Enfant" : "CHU Sainte-Justine",
              "Centre hospitalier universitaire de Montr\u00e9al" : "CHUM",
>>>>>>> 194a3912654ce34ffd033e787aa232046b56a814
              "LightspeedPOS" : "Lightspeed POS",
              "Lightspeed" : "Lightspeed POS",              
              "McGill (Centre for Medical Education)" : "McGill",
              "McGill university" : "McGill",
              "McGill University" : "McGill",
              "McGill University (Faculty of Medicine)" : "McGill",
              "McGill University / Morgan Stanley" : "McGill",
              "McGill University Health Centre" : "CUSM/MUHC",
              "McGill University and McGill University Health Centre" : "CUSM/MUHC",
              "McGill University, McGill University Health Centre" : "CUSM/MUHC",
              "McGill University, Montreal" : "McGill",
              "McGill University, Quartier de l'innovation (QI)" : "McGill",
<<<<<<< HEAD
              "Mcgill university" : "McGill",
              "Universite McGill" : "McGill",
              "Universit\u00e9 McGill" : "McGill",
              "V\u00e9zina et associ\u00e9s inc." : "V\u00e9zina & associ\u00e9s inc.",
              "\u00c9cole Polytechnique de Montreal" : "Ecole Polytechnique de Montr\u00e9al",
              "Polytechnique Montreal" : "Ecole Polytechnique de Montr\u00e9al",
              "Polytechnique de Montr\u00e9al" : "Ecole Polytechnique de Montr\u00e9al",
              "\u00c9cole Polytechnique de Montr\u00e9al" : "Ecole Polytechnique de Montr\u00e9al",
              "\u00c9cole de Technologie Sup\u00e9rieure" : "ETS Montr\u00e9al",
              "\u00c9cole de technologie sup\u00e9rieure" : "ETS Montr\u00e9al",
              "\u00c9TS" : "ETS Montr\u00e9al",
              "ETS" : "ETS Montr\u00e9al",
              "\u00c9TS Montreal" : "ETS Montr\u00e9al",
=======
              "V\u00e9zina et associ\u00e9s inc." : "V\u00e9zina & associ\u00e9s inc.",
              "\u00c9cole Polytechnique de Montreal" : u"\u00c9cole Polytechnique de Montr\u00e9al",
>>>>>>> 194a3912654ce34ffd033e787aa232046b56a814
              "F&.Co" : "F.&Co",
              "f. & co" : "F.&Co",
              "Frank and Oak" : "Frank & Oak",
              "Opal-RT Technologies" : "Opal-RT",
              "HEC MBA" : "HEC",
              "HEC Montreal" : "HEC",
              "HEC Montreal - Hacking Health" : "HEC",
              "HEC Montr\u00e9al" : "HEC",
<<<<<<< HEAD
              "HEC Montr\u00e9al" : "HEC",
              "hEC Montreal" : "HEC",
              "Centre Hospitalier Universitaire de Sherbrooke - CHUS" : "CHUS",
              "Centre Hospitalier Universitaire de Sherbrooke." : "CHUS",
              "Centre hospitalier universitaire de Sherbrooke" : "CHUS",
              "Centre medical Brunswick" : "Centre M\u00e9dical Brunswick",
              "Centre universitaire de sant\u00e9 McGill" : "CUSM/MUHC",
              "Desjardins (Groupe Technologies Desjardins)" : "Desjardins",
              "Desjardins Assurance" : "Desjardins",
              "Desjardins Assurances" : "Desjardins",
              "Desjardins Assurances Vie" : "Desjardins",
              "Desjardins Entreprise capital regional" : "Desjardins",
              "Desjardins Group" : "Desjardins",
              "Desjardins Group Insurance" : "Desjardins",
              "Desjardins Lab" : "Desjardins",
              "Desjardins S\u00e9curit\u00e9 Financi\u00e8re" : "Desjardins",
              "Desjardins capital" : "Desjardins",
              "Desjrdins" : "Desjardins",
              "Groupe Desjardins Technologique" : "Desjardins",
              "Groupe Technologie Desjardins" : "Desjardins",
              "Groupe Technologies Desjardins" : "Desjardins",
              "F\u00e9d\u00e9ration Desjardins" : "Desjardins",
              "F\u00e9d\u00e9ration des Caisses Desjardins" : "Desjardins",
              "Mouvement Desjardins" : "Desjardins",
              "District3" : "District 3",
              "Elekta Ltd." : "Elekta Ltd",
              "H\u00f4pital G\u00e9n\u00e9ral Juif" : "Jewish General Hospital",
              "Jewish General Hospital -- Pathology" : "Jewish General Hospital",
              "MUHC Jewish General" : "Jewish General Hospital",
              "MUHC and JGH" : "Jewish General Hospital",
              "Job seeker" : None,
              "CUSM" : "CUSM/MUHC",
              "MUHC" : "CUSM/MUHC",
              "MUHC RI" : "CUSM/MUHC",
              "RI MUHC" : "CUSM/MUHC",
              "Research institute muhc" : "CUSM/MUHC",
              "Insitut de recherche de CUSM" : "CUSM/MUHC",
              "Macadamian" : "Macadamian Technologies",
              "Montreal International" : "Montr\u00e9al International",
              "Hopital Maisonneuve-Rosemont" : "H\u00f4pital Maisonneuve-Rosemont",
              "Maisonneuve-Rosemont Hospital" : "H\u00f4pital Maisonneuve-Rosemont",
              "H\u00f4pital Rosemont-Maisonneuve" : "H\u00f4pital Maisonneuve-Rosemont",
              "McKinsey" : "McKinsey & Company",
              "Medfar Solutions MYLE EMR" : "Medfar Solutions Cliniques",
              "PwC" : "PricewaterhouseCoopers",
              "U de M" : "Universit\u00e9 de Montr\u00e9al",
              "UdeM" : "Universit\u00e9 de Montr\u00e9al",
              "UDEM" : "Universit\u00e9 de Montr\u00e9al",
              "UdM" : "Universit\u00e9 de Montr\u00e9al",
              "University of Montreal" : "Universit\u00e9 de Montr\u00e9al",
              "UQAM" : "UQ\u00c0M",
              "BELL CANADA - Bell Pratique sant\u00e9" : "Bell Canada",
              "Centre Medical Urbain" : "Centre M\u00e9dical Urbain",
              "College de Bois de Boulogne" :"Coll\u00e8ge Bois-de-Boulogne",
              "Espace Sant\u00e9 Innovation Montreal" : "Espace Sant\u00e9 Innovation de Montr\u00e9al",
              "IBM Cloud" : "IBM",
              "IBM Canada" : "IBM",
              "Icone Internationale" : "Ic\u00f4ne Internationale",
              "\u00c9ventium" : "Eventium",
              "JMSB Concordia University" : "Concordia",
              "Concordia University" : "Concordia",
=======
              "HEC Montréal" : "HEC",
              "Centre Hospitalier Universitaire de Sherbrooke - CHUS" : "CHUS",
              "Centre Hospitalier Universitaire de Sherbrooke." : "CHUS",
>>>>>>> 194a3912654ce34ffd033e787aa232046b56a814
              }


#AliasKeys = list(AliasDict.keys())+[i.upper() for i in AliasDict.keys()]
