# OrganizationAliases.py
# Try to solve the herculean task of people misspelling their company

AliasDict = { "360 Medlink" : "360Medlink",
              "ADNSolution" : "ADN Solution",
              "-" : None,
              "." : None,
              ":-}" : None,
              "None" : None,
              "self" : None,
              "freelance" : None,
              "free lance" : None,
              "n/a" : None,
              "Independent" : None,
              "Independent Contractor" : None,
              "Self-employed" : None,
              "Agence de la sante publique du Canada" : u"Agence de la santé publique du Canada",
              "Anges Quebec" : u"Anges Québec",
              "Association I.R.I.S. (Centre de crise)" : "Association IRIS",
              "BDC Healthcare Fund" : "BDC Venture Healthcare Fund",
              "BDC Venture Capital" : "BDC Venture Healthcare Fund",
              "BDC, Healthcare Fund" : "BDC Venture Healthcare Fund",
              "BDC Capital" : "BDC Venture Healthcare Fund",
              "CHU Sainte" : "CHU Sainte-Justine",
              "CHU Sainte Justine" : "CHU Sainte-Justine",
              "CHU Sainte-Justine Foundation" :"CHU Sainte-Justine",
              "CHU Ste Justine" : "CHU Sainte-Justine",
              "CHU ste Justine" : "CHU Sainte-Justine",
              "CHU Ste-Justine" : "CHU Sainte-Justine",
              "CHU-Ste-Justine" : "CHU Sainte-Justine",
              "Ste-Justine" : "CHU Sainte-Justine",
              "Ste-Justine MUCH" : "CHU Sainte-Justine",
              "chusjustine" : "CHU Sainte-Justine",
              "ste-justine hospital" : "CHU Sainte-Justine",
              u"centre de réadaptation marie enfant" : "CHU Sainte-Justine",
              "Chu St-Justine" : "CHU Sainte-Justine",
              "CHUSJ" : "CHU Sainte-Justine",
              "CCHU Sainte-Justine" : "CHU Sainte-Justine",
              "CHU Ste-Justine-Centre de réadaptation Marie-Enfant"      : "CHU Sainte-Justine",
              u"CHU Ste-Justine-Centre de réadaptation Marie-Enfant" : "CHU Sainte-Justine",
              "Centre d ePromotion de la Santé - CHU Sainte-Justine" : "CHU Sainte-Justine",
              "Centre de promotion de la santé CHU Sainte-Justine" : "CHU Sainte-Justine",
              "Centre de promotion de la sant\u00e9. CHU Sainte-Justine" : "CHU Sainte-Justine",
              "Centre hospitalier Universitaire Sainte Justine" : "CHU Sainte-Justine",
              "Hopital Sainte Justine" : "CHU Sainte-Justine",
              "Hopital Ste-Justine" : "CHU Sainte-Justine",
              "Hopital Ste-Justine, Centre de réadaptation Marie Enfant" : "CHU Sainte-Justine",
              u"Centre hospitalier universitaire de Montr\u00e9al" : "CHUM",
              "LightspeedPOS" : "Lightspeed POS",
              "McGill (Centre for Medical Education)" : "McGill",
              "McGill university" : "McGill",
              "McGill University" : "McGill",
              "McGill University (Faculty of Medicine)" : "McGill",
              "McGill University / Morgan Stanley" : "McGill",
              "McGill University Health Centre" : "McGill",
              "McGill University and McGill University Health Centre" : "McGill",
              "McGill University, McGill University Health Centre" : "McGill",
              "McGill University, Montreal" : "McGill",
              "McGill University, Quartier de l'innovation (QI)" : "McGill",
              u"V\u00e9zina et associ\u00e9s inc." : u"V\u00e9zina & associ\u00e9s inc.",
              u"\u00c9cole Polytechnique de Montreal" : u"\u00c9cole Polytechnique de Montr\u00e9al",
              "F&.Co" : "F.&Co",
              "f. & co" : "F.&Co",
              "Opal-RT Technologies" : "Opal-RT",
              "HEC MBA" : "HEC",
              "HEC Montreal" : "HEC",
              "HEC Montreal - Hacking Health" : "HEC",
              u"HEC Montr\u00e9al" : "HEC",
              u"HEC Montréal" : "HEC",
              }
